SCHOOL/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from primary import views

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="index.html"), name="index"),

    url(r'^school/create/$', views.create_school, name='create_school'),
    url(r'^school/update/(?P<pk>[0-9]+)/$', views.SchoolUpdateView.as_view(), name='update_school'),
    url(r'^school/list/$', views.SchoolListView.as_view(), name='list_school'),
    url(r'^school/update/address/(?P<address_id>[0-9]+)/(?P<school_id>[0-9]+)/$', views.school_address_update,
        name="school_address_update"),

    url(r'^school/subject/list/$', views.SubjectListView.as_view(), name='list_subject'),
    url(r'^school/subject/create/$', views.SubjectCreateView.as_view(), name='create_subject'),
    url(r'^school/subject/update/(?P<pk>[0-9]+)/$', views.SubjectUpdateView.as_view(), name='update_subject'),

    url(r'^class/class/create/$', views.ClassCreateView.as_view(), name='create_class'),
    url(r'^class/class/list/$', views.ClassListView.as_view(), name='list_class'),
    url(r'^class/class/update/(?P<pk>[0-9]+)/$', views.ClassUpdateView.as_view(), name='update_class'),

    # url(r'^class/student/subject/register/$', views.student_subject_register, name='select_subjects_save'),

    url(r'^class/student/search/$', views.searchStudent, name='search_student'),
    url(r'^class/student/register/(?P<student_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.classRegistration,
        name='register_class'),

    url(r'^school/create/teacher/$', views.create_teacher, name='create_teacher'),
    url(r'^school/create/parent/$', views.create_parent, name='create_parent'),
    url(r'^school/create/student/$', views.create_student, name='create_student'),
    # url(r'^school/update/student/(?P<pk>\d+)/$', views.StudentUpdate.as_view(), name='update_student'),
    url(r'^school/view/student/profile/$', views.profile_student, name='profile_student'),

    url(r'^school/view/student/detail/(?P<student_id>[0-9]+)/$', views.profile_student_details,
        name="profile_student_details"),
    url(r'^school/view/parent/detail/(?P<parent_id>[0-9]+)/$', views.profile_parent_details,
        name="profile_parent_details"),

    url(r'^school/view/student/update/(?P<student_id>[0-9]+)/$', views.profile_student_update,
        name="profile_student_update"),
    url(r'^school/view/parent/update/(?P<parent_id>[0-9]+)/$', views.profile_parent_update,
        name="profile_parent_update"),
    url(r'^school/view/teacher/update/(?P<teacher_id>[0-9]+)/$', views.profile_teacher_update,
        name="profile_teacher_update"),
    url(r'^teacher/list/$', views.TeacherListView.as_view(), name='list_teacher'),

    url(r'^school/view/parent/update/address/(?P<parent_id>[0-9]+)/(?P<address_id>[0-9]+)$',
        views.profile_parent_address_update, name="profile_parent_address_update"),
    url(r'^school/view/student/update/address/(?P<student_id>[0-9]+)/(?P<address_id>[0-9]+)$',
        views.profile_student_address_update, name="profile_student_address_update"),
    url(r'^school/view/student/$', views.StudentListView.as_view(), name='student'),
    url(r'^admin/', admin.site.urls),
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url('^accounts/', include('django.contrib.auth.urls')),
]

primary/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

from .models import School, Student, Address, Parent_Guardian, Teacher, Subject, Class, ClassName

import datetime, re

alnum_re = re.compile(r"^\w+$")


class SelectSubjectsForm(forms.Form):
    subjects = forms.ModelMultipleChoiceField(
        queryset=Class.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


"""
	def __init__(self, *args, **kwargs):
		self.classes = kwargs.pop('classes')
		print self.classes
		subject_id = Class.objects.filter(id__in = self.classes).values_list('subject')
		print subject_id
		super(SelectSubjectsForm, self).__init__(*args, **kwargs)
		self.fields['subject'] = forms.ModelMultipleChoiceField(
			widget = forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
			queryset = Class.objects.filter(id__in = self.classes).values_list('subject'),
			required = True
		)
"""


class ClassNameModelForm(forms.ModelForm):
    select_subjects = forms.CharField(max_length=10, widget=forms.HiddenInput(), initial='True')

    class Meta:
        model = ClassName
        fields = ('class_name',)

        def __init__(self, *args, **kwargs):
            super(ClassNameModelForm, self).__init__(*args, **kwargs)
            self.fields['class_name'].widget.attrs['class'] = 'form-control'


class ClassNameForm(forms.Form):
    class_name = forms.ModelChoiceField(queryset=ClassName.objects.all())
    select_subjects = forms.CharField(
        max_length=10,
        widget=forms.HiddenInput(),
        initial='False',
    )

    def __init__(self, *args, **kwargs):
        super(ClassNameForm, self).__init__(*args, **kwargs)
        self.fields['class_name'].widget.attrs['class'] = 'form-control'


class ClassRegistrationForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ('subject', 'class_name', 'teacher')

    def __init__(self, *args, **kwargs):
        super(ClassModelForm, self).__init__(*args, **kwargs)
        self.fields['subject'].widget.attrs['class'] = 'form-control'
        self.fields['teacher'].widget.attrs['class'] = 'form-control'
        self.fields['class_name'].widget.attrs['class'] = 'form-control'


class StudentSearchForm(forms.Form):
    first_name = forms.CharField(
        label=_("*First Name"),
        max_length=75,
        widget=forms.TextInput(),
        required=False
    )
    last_name = forms.CharField(
        label=_("*Last Name"),
        max_length=75,
        widget=forms.TextInput(),
        required=False
    )


class ClassModelForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ('subject', 'teacher', 'class_name', 'classDaysandTime', 'class_room')

    def __init__(self, *args, **kwargs):
        super(ClassModelForm, self).__init__(*args, **kwargs)
        self.fields['subject'].widget.attrs['class'] = 'form-control'
        self.fields['teacher'].widget.attrs['class'] = 'form-control'
        self.fields['class_name'].widget.attrs['class'] = 'form-control'
        self.fields['classDaysandTime'].widget.attrs['class'] = 'form-control'
        self.fields['class_room'].widget.attrs['class'] = 'form-control'


class SubjectModelForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ('subject',)

    def __init__(self, *args, **kwargs):
        super(SubjectModelForm, self).__init__(*args, **kwargs)
        self.fields['subject'].widget.attrs['class'] = 'form-control'


class TeacherModelForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ('gender', 'cell_phone', 'personal_email', 'personal_fax')

    def __init__(self, *args, **kwargs):
        super(TeacherModelForm, self).__init__(*args, **kwargs)
        self.fields['gender'].widget.attrs['class'] = 'form-control'
        self.fields['cell_phone'].widget.attrs['class'] = 'form-control'
        self.fields['personal_fax'].widget.attrs['class'] = 'form-control'
        self.fields['personal_email'].widget.attrs['class'] = 'form-control'


class SchoolModelForm(forms.ModelForm):
    class Meta:
        model = School
        fields = ('type', 'name', 'principal', 'email', 'fax')

    def __init__(self, *args, **kwargs):
        super(SchoolModelForm, self).__init__(*args, **kwargs)
        self.fields['type'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['principal'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['fax'].widget.attrs['class'] = 'form-control'


class ParentModelForm(forms.ModelForm):
    class Meta:
        model = Parent_Guardian
        fields = ('gender', 'cell_phone', 'personal_fax', 'work_name', 'work_phone', 'relationship')

    def __init__(self, *args, **kwargs):
        super(ParentModelForm, self).__init__(*args, **kwargs)
        self.fields['gender'].widget.attrs['class'] = 'form-control'
        self.fields['cell_phone'].widget.attrs['class'] = 'form-control'
        self.fields['personal_fax'].widget.attrs['class'] = 'form-control'
        self.fields['work_name'].widget.attrs['class'] = 'form-control'
        self.fields['work_phone'].widget.attrs['class'] = 'form-control'
        self.fields['relationship'].widget.attrs['class'] = 'form-control'


class AddressModelForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('street', 'town', 'city', 'country', 'phone')

    def __init__(self, *args, **kwargs):
        super(AddressModelForm, self).__init__(*args, **kwargs)
        self.fields['city'].widget.attrs['class'] = 'form-control'
        self.fields['town'].widget.attrs['class'] = 'form-control'
        self.fields['country'].widget.attrs['class'] = 'form-control'
        self.fields['street'].widget.attrs['class'] = 'form-control'
        self.fields['phone'].widget.attrs['class'] = 'form-control'


class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserModelForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'


class StudentModelForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('dob', 'gender', 'allergies', 'medical_conditions', 'religious_belief')

    def __init__(self, *args, **kwargs):
        super(StudentModelForm, self).__init__(*args, **kwargs)
        self.fields['dob'].widget.attrs['class'] = 'form-control'
        self.fields['gender'].widget.attrs['class'] = 'form-control'
        self.fields['allergies'].widget.attrs['class'] = 'form-control'
        self.fields['medical_conditions'].widget.attrs['class'] = 'form-control'
        self.fields['religious_belief'].widget.attrs['class'] = 'form-control'


RELATIONSHIP = (
    ('M', 'Mother'),
    ('F', 'Father'),
    ('B', 'Brother'),
    ('S', 'Sister'),
    ('A', 'Aunt'),
    ('U', 'Uncle'),
    ('G', 'Grand Parent'),
    ('C', 'Cousin'),
    ('L', 'Legal Guardian')
)

TYPE = (
    ('', ''),
    ('P', 'Primary School'),
    ('S', 'Secondary School'),
)


class CreateSchoolForm(forms.Form):
    street = forms.CharField(max_length=100)
    town = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)
    country = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=15, help_text='Please enter in the form as, 18681112222, no spaces or dashes',
                            label='School Phone')
    name = forms.CharField(max_length=100, label="School Name")
    principal = forms.CharField(max_length=100, label="Principal Full Name")
    email = forms.EmailField(label="School Email")
    fax = forms.CharField(max_length=15, required=False)
    type = forms.ChoiceField(
        label=_("*Type"),
        widget=forms.Select(),
        choices=TYPE,
        required=True
    )

    def clean_type(self):
        type = self.cleaned_data['type']

        # check to see is only alphanumberic values
        if (type == ''):
            raise forms.ValidationError("Type cannot be blank")
        return type

    def clean_street(self):
        street = self.cleaned_data['street']

        # check to see is only alphanumberic values
        if not re.match(r'^[A-Za-z0-9_]+( [A-Za-z0-9_]+)*$', street):
            raise forms.ValidationError("Street name must be alphanumberic characters only, such as 22 Me Street")
        return street

    def clean_town(self):
        town = self.cleaned_data['town']

        # check to see is only alpha values
        if not re.match(r'^[A-Za-z]+( [A-Za-z_]+)*$', town):
            raise forms.ValidationError("Town must contain only alpha characters only")
        return town

    def clean_city(self):
        city = self.cleaned_data['city']

        # check to see is only alpha values
        if not re.match(r'^[A-Za-z]+( [A-Za-z_]+)*$', city):
            raise forms.ValidationError("City must contain only alpha characters only")
        return city

    def clean_country(self):
        country = self.cleaned_data['country']

        # check to see is only alpha values
        if not re.match(r'^[A-Za-z]+( [A-Za-z_]+)*$', country):
            raise forms.ValidationError("Country must contain only alpha characters only")
        return country

    def clean_phone(self):
        phone = self.cleaned_data['phone']

        # check to see is only numeric values
        if not re.match(r'^[0-9]+$', phone):
            raise forms.ValidationError("Phone must contain only numeric characters only, no spaces or dashes")
        return phone


GENDER = (
    ('M', 'Male'),
    ('F', 'Female'),
)

SCHOOL/templates/class/class_create.html
{% extends "base.html" %}
{% block content %}

    <h1>Create New Class</h1>
	<form action="" method="post" class="form-horizontal">
		{% csrf_token %}
		{{form}}
		<input type='submit' value='Create'/>
	</form>
{% endblock %}

SCHOOL/templates/class/class_list.html
{% extends "base.html" %}
{% block content %}

    <h1>Classes</h1>
	<ul>
		{% for s in object_list %}
		<li> Teacher - {{s.teacher}}, Class Name- {{ s.class_name.class_name }}
		
		{% if s.class_name.class_departments %}
		 - {{ s.class_name.class_departments }}
		{% endif %}
		
		{% for p in s.subject.all %}
			,Subject - {{p.subject}}</li>
		{% endfor %}
		<li> <a href="/class/class/update/{{s.pk}}">Update Class</a></li>
		{% endfor %}
	</ul>
{% endblock %}

SCHOOL/templates/class/class_update_form.html
{% extends "base.html" %}
{% block content %}

    <h1>Update Class</h1>
	<form action="" method="post">
		{% csrf_token %}
		{{form}}
		<input type='submit' value='Update'/>
	</form>
{% endblock %}

SCHOOL/templates/class/select_subjects_form.html
{% extends "base.html" %}
{% block content %}

    <h1>Select Subjects</h1>

    <table class="table">
		<tr>
			<td>
				<h3>Select</h3>
			</td>
			
			<td>
				<h3>Subject</h3>
			</td>
			
			<td>
				<h3>Teacher</h3>
			</td>
			
			<td>
				<h3>Class</h3>
			</td>
			
			<td>
				<h3>Day and Times</h3>
			</td>
		</tr>
	
    <form action="" method="post" class='form-horizontal' name='SubjectRegisterForm'>
        {% csrf_token %}
		<input type='hidden' name='student' value='{{ student_id }}'/>
        {{form}}
    </form>
	</table>
{% endblock %}

SCHOOL/templates/class/student_registration.html
{% extends "base.html" %}
{% block content %}

    <h1>Class Registration</h1>
	<table class='table table-striped'>
	{% for s in student %}
		<tr>
			<th>Student Name </th>
			<th>Student DOB </th>
			<th>Student Current Class</th>
			<th>Parents</th>
			<th>Parents</th>
			<th>Register</th>
		</tr>
		<tr>
			<td> {{s.student.first_name}} {{s.student.last_name}} </td>
			<td> {{s.dob}} </td>
			{% if register %}
				{% for r in register %}
					<td>{{r.class_name}}</td>
				{% endfor %}
			{% else %}
				<td>New Student</td>
			{% endif %}
			{% for p in s.parent.all %}
			<td> {{p.parent}} </td>
			{% endfor %}
		</tr>
        <script>
            $(document).ready(function () {
                $('#id_class_name').prop('selectedIndex',0);
                $("#ckbCheckAll").removeAttr('checked');
                $("#ckbCheckAll").click(function () {
                    $(".checkBoxClass").prop('checked', $(this).prop('checked'));
                });

                $('.table').on('change', '#id_class_name', function () {
                    console.log('changed');
                    $("#ckbCheckAll").removeAttr('checked');
                    $(".checkBoxClass").removeAttr('checked');
                    // get class departments
                    $.get('{% url "register_class" s.id s.student.id %}' + '?class=' + $(this).val(), function(rdata){
                        var deparment_select = $('#department_dd');
                        var sub_table = $('#select_subjects');
                        deparment_select.empty();
                        sub_table.empty();
                        $.each(rdata, function(i, data){
                            sub_table.append('<tr><td><input type="checkbox" class="checkBoxClass" id="'+ data[4] +'"></td><td>'+ data[0] +'</td><td>'+ data[1]
                                +'</td><td>'+ data[2] +'</td><td>'+ data[3] +'</td></tr>')
                        });
                    }, "json");
                });

                $('.register-selected-classes').click(function () {
                    console.log($('#select_subjects').find('input[type="checkbox"]:checked'));
                    var selected_classes = [];
                    $('#select_subjects').find('input[type="checkbox"]:checked').each(function () {
                        console.log($(this).attr('id'));
                        selected_classes.push($(this).attr('id'))
                    });
                    $.get('{% url "register_class" s.id s.student.id %}' + '?reg_class=' + selected_classes, function(rdata){
                        location.reload();
                    });
                });
                
                $('.delete-subject').click(function () {
                    var del_row = $(this);
                    $.get('{% url "register_class" s.id s.student.id %}' + '?rc_del=' + $(this).attr('data-id'), function(){
                        console.log($(this));
                        del_row.parent().parent().remove();
                    });

                })
            });

        </script>
	{% endfor %}
	{% for s in school %}
		<td>{{ s.type }}</td>
{#		{% if s.type == 'P' %}#}
{#		#}
{#		<form action="" method="post" class='form-horizontal'>#}
{#        {% csrf_token %}#}
{#			<tr><td>{{form}}</td></tr>#}
{#			<tr><td><input type='Submit' value='Register'/></tr></td>#}
{#		</form>#}
{#		{% endif %}#}
		
		{% if s.type == 'S' %}
			<h3>If Student is of age to pick subjects such as in Form 3 or Form 4 Click Select Subjects Button</h3>
			<form action="" method="post" class='form-horizontal'>
			{% csrf_token %}
			<tr><td>{{form}}</td></tr>
{#			<tr><td><input type='Submit' value='Register'/></tr></td>#}
		</form>


		
{#		<form action="" method="post" class='form-horizontal'>#}
{#        {% csrf_token %}#}
{#            <tr><td><b>Department Name: </b></td><td>#}
{#            <select id="department_dd"></select>#}
{#        </td></tr>#}
{#		<tr><td><input type='Submit' value='Select Subjects'/></tr></td>#}
{#		</form>#}
		{% endif %}
	{% endfor %}
	</table>

    <table id="" class="table ">
        <tr>
            <th>Select<br/><input type="checkbox" id="ckbCheckAll" /></th>
            <th>Subject</th>
            <th>Teacher</th>
            <th>Class</th>
            <th>Day and Time</th>
        </tr>
    <tbody id="select_subjects">

    </tbody>
    <tr><td><a class="btn btn-default register-selected-classes">Register</a></td></tr>

    </table>

    <h1>Student already registered classes</h1>

    <table class="table">
    <tr>
        <th>Select</th>
        <th>Subject</th>
        <th>Teacher</th>
        <th>Class</th>
        <th>Day and Time</th>
        <th>Action</th>
    </tr>
    {% for rc in reg_classes %}
{#        {%  for sub in rc.class_name.subject.all %}#}
        <tr>
            <td><input type="checkbox" value="{{ rc.id }}"></td>
{#            <td>{{ sub }}</td>#}
            <td>
                {% for sub in rc.class_name.subject.all %}
                    {{ sub }},
                {% endfor %}</td>
            <td>{{ rc.class_name.teacher }}</td>
            <td>{{ rc.class_name }}</td>
            <td>{{ rc.class_name.classDaysandTime }}</td>
            <td><a class="btn delete-subject" data-id="{{ rc.id }}"><i class="glyphicon glyphicon-trash"></i></a></td>
        </tr>
{#        {% endfor %}#}
    {% endfor %}
    </table>

<script>

</script>

{% endblock %}

SCHOOL/templates/class/student_search.html
{% extends "base.html" %}
{% block content %}

    <h1>Find Student</h1>
	<form action="" method="post" class="form-horizontal">
		{% csrf_token %}
		{{form}}
		<input type='submit' value='Search'/>
	</form>
{% endblock %}

SCHOOL/templates/class/student_search_details.html
{% extends "base.html" %}
{% block content %}

    <h1>List Students</h1>
	<ul>
		{% if not student %}
			Nothing returned.
		{% endif %}
		{% for s in student %}
			<li> {{ s.student.first_name }}</li>
			<li> {{ s.student.last_name }}</li>
			<li> {{ s.dob }}</li>
			<!-- Must choose class first  -->
			{% for p in s.parent.all %}
				<li> {{ p }}</li>
			{% endfor %}
			{% for r in s.studentregisterclass_set.all %}
				<li>{{ r.class_name }}</li>
			{% endfor %}
			<li> <a href="/class/student/register/{{s.pk}}/{{s.student.id}}/">Register for Classes</a></li>
		{% endfor %}
	</ul>
{% endblock %}